services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-https
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - web

networks:
  web:
    driver: bridge
